const GITHUB_AUTH_TOKEN = ""
const BOT_NUMBER = "94776860011"
const SESSION_ID = "PRABATH-MD~Nz9DkaZY#rQuyvGSKX9iv6Ua_N45bXp_OI41fI8LugBQEV1dQduQ"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
