const GITHUB_AUTH_TOKEN = ""
const BOT_NUMBER = "94776860011"
const SESSION_ID = "PRABATH-MD~RStx2CaL#FhoDD2TK3k8klVYxC80thJvVyMcq3ZJEoHn2Eq4g1Uw"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
