const GITHUB_AUTH_TOKEN = ""
const BOT_NUMBER = "94765476552"
const SESSION_ID = "PRABATH-MD~xbcFBY5K#gOUbOfXdidzL2z3QrM7PKFvbELHkiptQ4OLVNaEUQoo"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
